import {LoginPage} from "../pages/login/login.page";
import {v1 as uuidV1} from "uuid";
import {CustomerAdministrationPage} from "../pages/customer/customer-administration.page";
import {CustomerManageDialog} from "../pages/customer/customer-manage.dialog";


describe('customer-management', () => {

  it('allows to create and update customers', () => {
    let loginPage = new LoginPage();
    loginPage.open();
    let welcomeComponentPage = loginPage.loginWithDefaultCredentials();
    let customerPage = welcomeComponentPage.getNavigation().navigateToPage('Stammdaten', new CustomerAdministrationPage());
    let customerManageDialog = customerPage.openCreateDialog();
    const randomUuid = uuidV1();
    const initialFirstname = `CYPRESS-FIRSTNAME-${randomUuid}`;
    const initialLastname = `CYPRESS-LASTNAME-${randomUuid}`;
    const initialEmail = `CYPRESS-EMAIL-${randomUuid}@cypress.com`;
    const initialAddress = `CYPRESS-ADDRESS-${randomUuid}`;
    const initialPostalCode = Math.floor(Math.random() * (99999 - 1)) + 1;
    const initialCity = `CYPRESS-CITY-${randomUuid}`;
    const initialPrivatePhone = `+49-${Math.floor(Math.random() * (99999 - 1)) + 1}-${Math.floor(Math.random() * (99999 - 1)) + 1}`;
    const initialBusinessPhone = `+49-${Math.floor(Math.random() * (99999 - 1)) + 1}-${Math.floor(Math.random() * (99999 - 1)) + 1}`;
    const initialMobilePhone = `+49-${Math.floor(Math.random() * (9999 - 1)) + 1}-${Math.floor(Math.random() * (999999999 - 1)) + 1}`;
    const initialBirthday = new Date();
    const initialAdditionalInfo = `CYPRESS-ADDITIONAL-INFO-${randomUuid}\nNEXT-LINE`;
    const initialMedicalInfo = `CYPRESS-MEDICAL-INFO-${randomUuid}\nNEXT-LINE`;
    const initialAllergyInfo = `CYPRESS-ALLERGY-INFO-${randomUuid}\nNEXT-LINE`;
    const initialEyeDisease = `CYPRESS-EYE-DISEASE-${randomUuid}\nNEXT-LINE`;
    const initialOnFirstNameBasis = true;
    const initialHayFever = true;
    const initialPlasterAllergy = true;
    const initialCyanoacrylateAllergy = true;
    const initialAsthma = true;
    const initialDryEyes = true;
    const initialCirculationProblems = true;
    const initialEpilepsy = true;
    const initialDiabetes = true;
    const initialClaustrophobia = true;
    const initialNeurodermatitis = true;
    const initialGlasses = true;
    const initialCovid19Vaccinated = true;
    const initialContacts = true;
    customerManageDialog.writeFirstName(initialFirstname);
    customerManageDialog.writeLastName(initialLastname);
    customerManageDialog.writeEmail(initialEmail);
    customerManageDialog.writeAddress(initialAddress);
    customerManageDialog.writePostalCode(initialPostalCode);
    customerManageDialog.writeCity(initialCity);
    customerManageDialog.writePrivatePhone(initialPrivatePhone);
    customerManageDialog.writeBusinessPhone(initialBusinessPhone);
    customerManageDialog.writeMobilePhone(initialMobilePhone);
    customerManageDialog.writeBirthday(initialBirthday);
    customerManageDialog.writeOnFirstNameBasis(initialOnFirstNameBasis);
    customerManageDialog.writeAdditionalInfo(initialAdditionalInfo);
    customerManageDialog.writeMedicalInfo(initialMedicalInfo);
    customerManageDialog.writeHayFever(initialHayFever);
    customerManageDialog.writePlasterAllergy(initialPlasterAllergy);
    customerManageDialog.writeCyanoacrylateAllergy(initialCyanoacrylateAllergy);
    customerManageDialog.writeAllergy(initialAllergyInfo);
    customerManageDialog.writeAsthma(initialAsthma);
    customerManageDialog.writeDryEyes(initialDryEyes);
    customerManageDialog.writeEyeDisease(initialEyeDisease);
    customerManageDialog.writeCirculationProblems(initialCirculationProblems);
    customerManageDialog.writeEpilepsy(initialEpilepsy);
    customerManageDialog.writeDiabetes(initialDiabetes);
    customerManageDialog.writeClaustrophobia(initialClaustrophobia);
    customerManageDialog.writeNeurodermatitis(initialNeurodermatitis);
    customerManageDialog.writeContacts(initialContacts);
    customerManageDialog.writeGlasses(initialGlasses);
    customerManageDialog.writeCovid19Vaccinated(initialCovid19Vaccinated);
    customerManageDialog.saveChanges(true);
    customerManageDialog = customerPage.getPageSearch().searchAndOpen(initialFirstname, new CustomerManageDialog()) as CustomerManageDialog;
    customerManageDialog.validateFirstNameEquality(initialFirstname);
    customerManageDialog.validateLastNameEquality(initialLastname);
    customerManageDialog.validateEmailEquality(initialEmail);
    customerManageDialog.validateAddressEquality(initialAddress);
    customerManageDialog.validatePostalCodeEquality(initialPostalCode);
    customerManageDialog.validateCityEquality(initialCity);
    customerManageDialog.validatePrivatePhoneEquality(initialPrivatePhone);
    customerManageDialog.validateBusinessPhoneEquality(initialBusinessPhone);
    customerManageDialog.validateMobilePhoneEquality(initialMobilePhone);
    customerManageDialog.validateBirthdayEquality(initialBirthday);
    customerManageDialog.validateOnFirstNameBasisEquality(initialOnFirstNameBasis);
    customerManageDialog.validateAdditionalInfoEquality(initialAdditionalInfo);
    customerManageDialog.validateMedicalInfoEquality(initialMedicalInfo);
    customerManageDialog.validateHayFeverEquality(initialHayFever);
    customerManageDialog.validatePlasterAllergyEquality(initialPlasterAllergy);
    customerManageDialog.validateCyanoacrylateAllergyEquality(initialCyanoacrylateAllergy);
    customerManageDialog.validateAllergyEquality(initialAllergyInfo);
    customerManageDialog.validateAsthmaEquality(initialAsthma);
    customerManageDialog.validateDryEyesEquality(initialDryEyes);
    customerManageDialog.validateEyeDiseaseEquality(initialEyeDisease);
    customerManageDialog.validateCirculationProblemsEquality(initialCirculationProblems);
    customerManageDialog.validateEpilepsyEquality(initialEpilepsy);
    customerManageDialog.validateDiabetesEquality(initialDiabetes);
    customerManageDialog.validateClaustrophobiaEquality(initialClaustrophobia);
    customerManageDialog.validateNeurodermatitisEquality(initialNeurodermatitis);
    customerManageDialog.validateContactsEquality(initialContacts);
    customerManageDialog.validateGlassesEquality(initialGlasses);
    customerManageDialog.validateCovid19VaccinatedEquality(initialCovid19Vaccinated);
    customerManageDialog.close()
    customerManageDialog = customerPage.getPageSearch().searchAndOpen(initialLastname, new CustomerManageDialog()) as CustomerManageDialog;
    customerManageDialog.validateFirstNameEquality(initialFirstname);
    customerManageDialog.validateLastNameEquality(initialLastname);
    customerManageDialog.validateEmailEquality(initialEmail);
    customerManageDialog.validateAddressEquality(initialAddress);
    customerManageDialog.validatePostalCodeEquality(initialPostalCode);
    customerManageDialog.validateCityEquality(initialCity);
    customerManageDialog.validatePrivatePhoneEquality(initialPrivatePhone);
    customerManageDialog.validateBusinessPhoneEquality(initialBusinessPhone);
    customerManageDialog.validateMobilePhoneEquality(initialMobilePhone);
    customerManageDialog.validateBirthdayEquality(initialBirthday);
    customerManageDialog.validateOnFirstNameBasisEquality(initialOnFirstNameBasis);
    customerManageDialog.validateAdditionalInfoEquality(initialAdditionalInfo);
    customerManageDialog.validateMedicalInfoEquality(initialMedicalInfo);
    customerManageDialog.validateHayFeverEquality(initialHayFever);
    customerManageDialog.validatePlasterAllergyEquality(initialPlasterAllergy);
    customerManageDialog.validateCyanoacrylateAllergyEquality(initialCyanoacrylateAllergy);
    customerManageDialog.validateAllergyEquality(initialAllergyInfo);
    customerManageDialog.validateAsthmaEquality(initialAsthma);
    customerManageDialog.validateDryEyesEquality(initialDryEyes);
    customerManageDialog.validateEyeDiseaseEquality(initialEyeDisease);
    customerManageDialog.validateCirculationProblemsEquality(initialCirculationProblems);
    customerManageDialog.validateEpilepsyEquality(initialEpilepsy);
    customerManageDialog.validateDiabetesEquality(initialDiabetes);
    customerManageDialog.validateClaustrophobiaEquality(initialClaustrophobia);
    customerManageDialog.validateNeurodermatitisEquality(initialNeurodermatitis);
    customerManageDialog.validateContactsEquality(initialContacts);
    customerManageDialog.validateGlassesEquality(initialGlasses);
    customerManageDialog.validateCovid19VaccinatedEquality(initialCovid19Vaccinated);

    const initialFirstnameChanged = `${initialFirstname}-changed`;
    const initialLastnameChanged = `${initialLastname}-changed`;
    const initialEmailChanged = `changed-${initialEmail}`;
    const initialAddressChanged = `${initialAddress}-changed`;
    const initialPostalCodeChanged = Math.floor(Math.random() * (99999 - 1)) + 1;
    const initialCityChanged = `${initialCity}-changed`;
    const initialPrivatePhoneChanged = `+49-${Math.floor(Math.random() * (99999 - 1)) + 1}-${Math.floor(Math.random() * (99999 - 1)) + 1}`;
    const initialBusinessPhoneChanged = `+49-${Math.floor(Math.random() * (99999 - 1)) + 1}-${Math.floor(Math.random() * (99999 - 1)) + 1}`;
    const initialMobilePhoneChanged = `+49-${Math.floor(Math.random() * (9999 - 1)) + 1}-${Math.floor(Math.random() * (999999999 - 1)) + 1}`;
    const initialBirthdayChanged = new Date(Math.floor(Math.random() * (2099 - 2000)) + 2000, Math.floor(Math.random() * (11)), Math.floor(Math.random() * (28 - 1)) + 1);
    const initialAdditionalInfoChanged = `${initialAdditionalInfo}\nchanged`;
    const initialMedicalInfoChanged = `${initialMedicalInfo}\nchanged`;
    const initialAllergyInfoChanged = `${initialAllergyInfo}\nchanged`;
    const initialEyeDiseaseChanged = `${initialEyeDisease}\nchanged`;
    const initialOnFirstNameBasisChanged = !initialOnFirstNameBasis;
    const initialHayFeverChanged = !initialHayFever;
    const initialPlasterAllergyChanged = !initialPlasterAllergy;
    const initialCyanoacrylateAllergyChanged = !initialCyanoacrylateAllergy;
    const initialAsthmaChanged = !initialAsthma;
    const initialDryEyesChanged = !initialDryEyes;
    const initialCirculationProblemsChanged = !initialCirculationProblems;
    const initialEpilepsyChanged = !initialEpilepsy;
    const initialDiabetesChanged = !initialDiabetes;
    const initialClaustrophobiaChanged = !initialClaustrophobia;
    const initialNeurodermatitisChanged = !initialNeurodermatitis;
    const initialGlassesChanged = !initialGlasses;
    const initialCovid19VaccinatedChanged = !initialCovid19Vaccinated;
    const initialContactsChanged = !initialContacts;

    customerManageDialog.writeFirstName(initialFirstnameChanged);
    customerManageDialog.writeLastName(initialLastnameChanged);
    customerManageDialog.writeEmail(initialEmailChanged);
    customerManageDialog.writeAddress(initialAddressChanged);
    customerManageDialog.writePostalCode(initialPostalCodeChanged);
    customerManageDialog.writeCity(initialCityChanged);
    customerManageDialog.writePrivatePhone(initialPrivatePhoneChanged);
    customerManageDialog.writeBusinessPhone(initialBusinessPhoneChanged);
    customerManageDialog.writeMobilePhone(initialMobilePhoneChanged);
    customerManageDialog.writeBirthday(initialBirthdayChanged);
    customerManageDialog.writeOnFirstNameBasis(initialOnFirstNameBasisChanged);
    customerManageDialog.writeAdditionalInfo(initialAdditionalInfoChanged);
    customerManageDialog.writeMedicalInfo(initialMedicalInfoChanged);
    customerManageDialog.writeHayFever(initialHayFeverChanged);
    customerManageDialog.writePlasterAllergy(initialPlasterAllergyChanged);
    customerManageDialog.writeCyanoacrylateAllergy(initialCyanoacrylateAllergyChanged);
    customerManageDialog.writeAllergy(initialAllergyInfoChanged);
    customerManageDialog.writeAsthma(initialAsthmaChanged);
    customerManageDialog.writeDryEyes(initialDryEyesChanged);
    customerManageDialog.writeEyeDisease(initialEyeDiseaseChanged);
    customerManageDialog.writeCirculationProblems(initialCirculationProblemsChanged);
    customerManageDialog.writeEpilepsy(initialEpilepsyChanged);
    customerManageDialog.writeDiabetes(initialDiabetesChanged);
    customerManageDialog.writeClaustrophobia(initialClaustrophobiaChanged);
    customerManageDialog.writeNeurodermatitis(initialNeurodermatitisChanged);
    customerManageDialog.writeContacts(initialContactsChanged);
    customerManageDialog.writeGlasses(initialGlassesChanged);
    customerManageDialog.writeCovid19Vaccinated(initialCovid19VaccinatedChanged);
    customerManageDialog.saveChanges(false);

    customerManageDialog = customerPage.getPageSearch().searchAndOpen(initialLastnameChanged, new CustomerManageDialog()) as CustomerManageDialog;
    customerManageDialog.validateFirstNameEquality(initialFirstnameChanged);
    customerManageDialog.validateLastNameEquality(initialLastnameChanged);
    customerManageDialog.validateEmailEquality(initialEmailChanged);
    customerManageDialog.validateAddressEquality(initialAddressChanged);
    customerManageDialog.validatePostalCodeEquality(initialPostalCodeChanged);
    customerManageDialog.validateCityEquality(initialCityChanged);
    customerManageDialog.validatePrivatePhoneEquality(initialPrivatePhoneChanged);
    customerManageDialog.validateBusinessPhoneEquality(initialBusinessPhoneChanged);
    customerManageDialog.validateMobilePhoneEquality(initialMobilePhoneChanged);
    customerManageDialog.validateBirthdayEquality(initialBirthdayChanged);
    customerManageDialog.validateOnFirstNameBasisEquality(initialOnFirstNameBasisChanged);
    customerManageDialog.validateAdditionalInfoEquality(initialAdditionalInfoChanged);
    customerManageDialog.validateMedicalInfoEquality(initialMedicalInfoChanged);
    customerManageDialog.validateHayFeverEquality(initialHayFeverChanged);
    customerManageDialog.validatePlasterAllergyEquality(initialPlasterAllergyChanged);
    customerManageDialog.validateCyanoacrylateAllergyEquality(initialCyanoacrylateAllergyChanged);
    customerManageDialog.validateAllergyEquality(initialAllergyInfoChanged);
    customerManageDialog.validateAsthmaEquality(initialAsthmaChanged);
    customerManageDialog.validateDryEyesEquality(initialDryEyesChanged);
    customerManageDialog.validateEyeDiseaseEquality(initialEyeDiseaseChanged);
    customerManageDialog.validateCirculationProblemsEquality(initialCirculationProblemsChanged);
    customerManageDialog.validateEpilepsyEquality(initialEpilepsyChanged);
    customerManageDialog.validateDiabetesEquality(initialDiabetesChanged);
    customerManageDialog.validateClaustrophobiaEquality(initialClaustrophobiaChanged);
    customerManageDialog.validateNeurodermatitisEquality(initialNeurodermatitisChanged);
    customerManageDialog.validateContactsEquality(initialContactsChanged);
    customerManageDialog.validateGlassesEquality(initialGlassesChanged);
    customerManageDialog.validateCovid19VaccinatedEquality(initialCovid19VaccinatedChanged);
    customerManageDialog.close();
  })

})
