insert into koku.user_region (country_name, country_iso, state_name, state_iso) VALUES
 ('Deutschland', 'DE', 'Brandenburg','BB'),
 ('Deutschland', 'DE', 'Berlin','BE'),
 ('Deutschland', 'DE', 'Baden-Württemberg','BW'),
 ('Deutschland', 'DE', 'Bayern','BY'),
 ('Deutschland', 'DE', 'Hansestadt Bremen','HB'),
 ('Deutschland', 'DE', 'Hessen','HE'),
 ('Deutschland', 'DE', 'Hansestadt Hamburg','HH'),
 ('Deutschland', 'DE', 'Mecklenburg Vorpommern','MV'),
 ('Deutschland', 'DE', 'Niedersachsen','NI'),
 ('Deutschland', 'DE', 'Nordrhein-Westfalen','NW'),
 ('Deutschland', 'DE', 'Rheinland-Pfalz','RP'),
 ('Deutschland', 'DE', 'Schleswig-Holstein','SH'),
 ('Deutschland', 'DE', 'Saarland','SL'),
 ('Deutschland', 'DE', 'Sachsen','SN'),
 ('Deutschland', 'DE', 'Sachsen-Anhalt','ST'),
 ('Deutschland', 'DE', 'Thüringen','TH'),

 ('Österreich', 'AT', 'Burgenland','1'),
 ('Österreich', 'AT', 'Kärnten','2'),
 ('Österreich', 'AT', 'Niederösterreich','3'),
 ('Österreich', 'AT', 'Oberösterreich','4'),
 ('Österreich', 'AT', 'Land Salzburg','5'),
 ('Österreich', 'AT', 'Steiermark','6'),
 ('Österreich', 'AT', 'Tirol','7'),
 ('Österreich', 'AT', 'Vorarlberg','8'),
 ('Österreich', 'AT', 'Wien','9'),

 ('Schweiz', 'CH', 'Kanton Zürich','ZH'),

 ('Schweiz', 'CH', 'Kanton Bern','BE'),
 ('Schweiz', 'CH', 'Kanton Luzern','LU'),
 ('Schweiz', 'CH', 'Kanton Uri','UR'),
 ('Schweiz', 'CH', 'Kanton Schwyz','SZ'),
 ('Schweiz', 'CH', 'Kanton Obwalden','OW'),
 ('Schweiz', 'CH', 'Kanton Nidwalden','NW'),
 ('Schweiz', 'CH', 'Kanton Glarus','GL'),
 ('Schweiz', 'CH', 'Kanton Zug','ZG'),
 ('Schweiz', 'CH', 'Canton de Fribourg','FR'),
 ('Schweiz', 'CH', 'Kanton Solothurn','SO'),
 ('Schweiz', 'CH', 'Kanton Basel-Stadt','BS'),
 ('Schweiz', 'CH', 'Kanton Basel-Landschaft','BL'),
 ('Schweiz', 'CH', 'Kanton Schaffhausen','SH'),
 ('Schweiz', 'CH', 'Kanton Appenzell Ausserrhoden','AR'),
 ('Schweiz', 'CH', 'Kanton Appenzell Innerrhoden','AI'),
 ('Schweiz', 'CH', 'Kanton St. Gallen','SG'),
 ('Schweiz', 'CH', 'Kanton Graubünden','GR'),
 ('Schweiz', 'CH', 'Kanton Aargau','AG'),
 ('Schweiz', 'CH', 'Kanton Thurgau','TG'),
 ('Schweiz', 'CH', 'Canton Ticino','TI'),
 ('Schweiz', 'CH', 'Canton de Vaud','VD'),
 ('Schweiz', 'CH', 'Canton du Valais','VS'),
 ('Schweiz', 'CH', 'Canton de Neuchâtel','NE'),
 ('Schweiz', 'CH', 'Canton de Genève','GE'),
 ('Schweiz', 'CH', 'Canton du Jura','JU')
 ;