spring:
  application:
    name: @project.artifactId@
  profiles:
    active:
      - logging
  config:
    import: ${CONFIG_IMPORT_SOURCE:configserver:http://localhost:8110}

server:
  port: 8200
  ssl:
    enabled: true
    certificate: /ssl/ssl_certificate.crt
    certificate-private-key: /ssl/ssl_certificate.key

