spring:
  batch:
    initialize-schema: embedded
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: 'postgres'
    password: 'koku'
    platform: postgres
  flyway:
    enabled: true
    baseline-on-migrate: false
    default-schema: koku
    schemas:
      - koku
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          schema-generation:
            scripts:
            #create-target: create.sql
            #create-source: metadata
            #action: create