spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/koku
    username: 'postgres'
    password: 'koku'
  flyway:
    enabled: true
    baseline-on-migrate: false
    default-schema: koku
    schemas:
      - koku
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        metadata_builder_contributor: de.domschmidt.koku.db_ext.PostgresFunctionRegister
    hibernate:
      ddl:
        auto: none
  sql:
    init:
      platform: postgres
  batch:
    jdbc:
      initialize-schema: embedded