name: main
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: SemRel
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@16ca923e6ccbb50770c415a0ccd43709a8c5f7a4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@6c4e9964d4ecb8f1026310cd8618791fd51a8016
        with:
          java-version: 21
          java-distribution: 'temurin'

      - name: Set Maven Version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: "mvn versions:set -DnewVersion=${{steps.semantic.outputs.new_release_version}}"

      - name: Maven Build
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          DH_USERNAME: ${{ secrets.DH_USERNAME }}
          DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
        run: "mvn install -Djib.to.auth.username=${DH_USERNAME} -Djib.to.auth.password=${DH_PASSWORD} -P jib-build"

      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          context: koku-frontend
          push: true
          tags: domschmidt/koku-frontend:${{steps.semantic.outputs.new_release_version}}
